/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(iirNotch.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(53b0ee3e3b6ee2d46bbfb5a4d55193de)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <notchFilter/iirNotch.h>
// pydoc.h is automatically generated in the build directory
#include <iirNotch_pydoc.h>

void bind_iirNotch(py::module& m)
{

    using iirNotch    = gr::notchFilter::iirNotch;


    py::class_<iirNotch, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<iirNotch>>(m, "iirNotch", D(iirNotch))

        .def(py::init(&iirNotch::make),
           D(iirNotch,make)
        )
        



        ;




}








